name: CI

on:
  pull_request:
    paths-ignore:
    - '**.md'
  push:
    paths-ignore:
    - '**.md'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        emacs_version: [27.2, 28.2, 29.3, snapshot]
        python_version: [3.12.4, 3.x]
        include:
          - os: macos-latest
            emacs_version: snapshot
            python_version: 3.x
    steps:
    - uses: actions/checkout@v4
    - uses: purcell/setup-emacs@master
      with:
        version: ${{ matrix.emacs_version }}
    - uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python_version }}
        cache: 'pip'
    # https://github.com/itamarst/gha-upload-cores/blob/main/.github/workflows/build.yml
    - run: |
        sudo mkdir /cores
        sudo chmod 777 /cores
        # Core filenames will be of the form executable.pid.timestamp:
        sudo bash -c 'echo "/cores/%e.%p.%t" > /proc/sys/kernel/core_pattern'
    - run: 'pip install -r requirements.txt'
    - run: 'make test'
    - uses: actions/upload-artifact@v4
      if: ${{ failure() }}  # Run only if something went wrong
      with:
        name: cores
        path: /cores
